### ISSUE TITLE
Do not default to binary updates for Git checkouts

### ISSUE THREAD

**Issue by TheLastProject** [redeclipse/base#100]
When doing a Git checkout, the default should be set as follows (on Linux at least): REDECLIPSE_BRANCH=source

**Comment by freezurbern** [comment]
Please, only do this for Linux. On Windows it is obviously very helpful. There's also more than a couple people who use the git version but aren't exactly 'devs' so they don't want to worry with compiling.

**Comment by qreeves** [comment]
Default branch is now `devel` which doesn't clobber game data but grabs binaries. It is considered that anyone wanting to build from source has the expertise to change the branch.
