### ISSUE TITLE
Viewing spectv within editmode, breaks spectv in other game modes

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1038]
- Version and build: current master
- Observation: viewing/testing spectv camera views within editing, will break spectv in other game modes so that the camera never changes.
- How to reproduce: 
  - view spectv on a map with camera entities
  - cycle through cameras
  - switch to another game mode (eg; ffa)
  - the automatic spectv camera is locked to the current/manually selected camera and will not change

Only workaround is to exit/restart the game.

**Comment by Jigoku** [comment]
Figured out what was causing this... i had set spectvmintime/spectvmaxtime to ridiculously high values and completely forgot about it... closing.

**Comment by Jigoku** [comment]
Can somebody else confirm this problem? It seems to still be happening at times regardless of spectvmin/max time values.

**Comment by qreeves** [comment]
I have an idea what it could be, and it is likely that you are correct in reporting this as an issue. Will get to it eventually, so just leave it open 😛

**Comment by Jigoku** [comment]
Looks like this fixed it: https://github.com/redeclipse/base/commit/6b23bfbb9966f0ecafe96e25ab3deb40f0d26ac6
