### ISSUE TITLE
texture browser doesn't grab input when typing

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1039]
Texture menu should probably grab input after clicking the search box, as to stop unexpected changes to the map in editing.

- Version and build: master
- Observation: filtering textures by a search string will resize the texture menu depending on few results, problematic as for when the mouse isn't hovering over the search box, input becomes editbind actions instead. Due to the texture menu resizing, this causes you to place/delete things in the map. 

- How to reproduce: search for a specific texture in texture browser, or move the mouse away from the search box.

![2020-04-21-161855_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/79883905-5df3ca00-83ec-11ea-81e4-4e00ec4e496f.png)

**Comment by Dziq84** [comment]
this is a problem with every input box in any menu ;o

**Comment by lambda-11235** [comment]
My current approach is
1. Move the cursor over the text box.
2. Let go carefully so as not to bump the mouse off of the box.
3. Go back to 1 because I messed up 2.

**Comment by Jigoku** [comment]
Closing; no longer relevant as for recent editor overhaul.
