### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [redeclipse/base#1041]
i have downloaded version 2.0 but it claims to be version 1.9:

<img width="255" alt="Screenshot 2020-04-23 at 22 01 51" src="https://user-images.githubusercontent.com/1261954/80144097-30567e80-85ae-11ea-96ea-43d9a1bea555.png">
<img width="457" alt="Screenshot 2020-04-23 at 22 01 42" src="https://user-images.githubusercontent.com/1261954/80144102-32b8d880-85ae-11ea-9000-9896958ab432.png">
<img width="614" alt="Screenshot 2020-04-23 at 22 02 09" src="https://user-images.githubusercontent.com/1261954/80144106-34829c00-85ae-11ea-8632-79fa2c3d78b2.png">

**Comment by qreeves** [comment]
Yeah, I probably forgot in the rush on release day as updating the Info.plist is manual, will fix in 2.2.
