### ISSUE TITLE
method to control vpalette strength

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1070]
`vpalette` textures are easily under used, due to many texures end up looking over saturated and sometimes out of place when considering lighting etc.

It would be nice to have something along the lines of `vpalettescale` to control how saturated the palette colour is when multiplied with the diffuse texture.

**Comment by qreeves** [comment]
```C++
vec getcolorscale() const { return palette || palindex ? vec(colorscale).mul(game::getpalette(palette, palindex)) : colorscale; }
```
You can still use `vcolour` when using `vpalette`, they get multiplied together. If this solves your issue, feel free to close it.

**Comment by Jigoku** [comment]
Oh that's a good point :+1:
