### ISSUE TITLE
Entity billboard font becomes darkened depending on world settings

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1079]
Changing `hdrbright` / `sunlightscale` results in the entity billboard changing colours, which can sometimes be quite hard to read; 

See screenshot:
![2020-07-17-161259_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/87825130-713cf700-c86e-11ea-831a-652ab9d0332b.png)

**Comment by q009** [comment]
No longer relevant
