### ISSUE TITLE
Mapmodels sometimes being culled when they shouldn't be

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1091]
Mapmodels are sometimes occluded/culled when they shouldn't be;
Here's a clip showing the problem:
https://cdn.discordapp.com/attachments/274036564970176512/744845158557941820/out-2020-08-17_10.06.59-2.mp4

**Comment by qreeves** [comment]
Is the model origin inside the geometry or something? The way that flickers in and out doesn't seem normal somehow.

**Comment by Jigoku** [comment]
I don't think so, but there is a collision issue with mapmodels that are scaled up past 100. 
I believe this started happening after this commit: https://github.com/redeclipse/base/commit/0c22d1edb3c833454f84ef78dd9fae0e09d3ad32

Some mapmodels don't physically collide well since then; for example: https://cdn.discordapp.com/attachments/498289668589223966/726693819856453662/20200628080038.png

I wonder if the origin is off center when model is scaled up past 100, assuming that part of the code is also used for visibility collision (when deciding to cull models?)

**Comment by qreeves** [comment]
Yeah I noticed something was off when I booted up the game earlier, will have to add this to my todo list.

**Comment by SniperGoth** [comment]
Yep, this completelly broke one of my maps, the rats one.
Scaling up models "inverts" the collision.

**Comment by Jigoku** [comment]
Should be fixed in: https://github.com/redeclipse/base/commit/e0b887eddaf39916087e871153baca41cf9cfe6f
@SniperGoth if you wanted to confirm your rats map is all working again, then i'll close this issue.
