### ISSUE TITLE
"no parkour" material, disappears after calclight in some cases

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1098]
When placing the material combination `clip` and `ladder`, it disallows parkour as expected, but once calclight/remip is done, the entire material volume disappears. This only seems to happen when the material volume is equal to the size of the geometry (flat surfaces, entire cubes, etc)

To reproduce; 
* add `clip`  and `ladder` material so it's contained within a whole cube / flat geometry
* do a `calclight`
* materials disappear

**Comment by dc-de** [comment]
This happens every time on purge!

**Comment by Calinou** [comment]
I believe the engine optimizes out materials if they're fully inside solid geometry. I see two ways to solve this:

- Push your wall slightly so the clip + ladder isn't fully in solid geometry (or add a thin layer of clip + ladder in front of it).
- Change the engine so `gameclip` + `ladder` is used to signify "no parkour" areas, and place the material in front of where you want to avoid parkour. This way, the material doesn't have to be placed in solid geometry anymore.

**Comment by qreeves** [comment]
The material won't work unless the player can end up inside it anyway, as the `inmaterial` check literally needs them to be in the material. If a cube is fully solid there's no possibility to be in the material anyway, so the material gets optimised out. If you want a surface to use a material property you need to extend it out away from the cube.

This isn't a bug, so I'm going to close it, but if there's anything else please feel free to ask.

**Comment by Jigoku** [comment]
Makes sense. @dc-de pointed this out on his purge map, wasn't sure how it was supposed to be implemented in case of flat geometry, so he'll have to extend the material out from the cubes :+1:
