### ISSUE TITLE
able to join private server without a password

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1101]
It's possible to connect to a private server, without entering the password.

_docs/examples/servinit.cfg_ mentions these two entries:

> // serverpass "p4ssw0rd" // server password required to successfully connect, used for private servers, THIS IS NOT THE ADMIN PASSWORD

> // adminpass "4dm1np4ss" // server password for administrators (change the password to your own, of course)
//       to gain access this way, go in game, connect to your server, and use /setmaster 4dm1np4ss

However; When setting this, the server appears as private listed in the server browser, but you can still connect with a blank or incorrect password:
```
serverpass "p4ssw0rd"
sv_serveropen 0
```

**Comment by qreeves** [comment]
Are you sure you're not using your authkey to override it?

**Comment by Jigoku** [comment]
IIRC, i did try with a fresh home folder where no authkey was set, and it still happened.

**Comment by Jigoku** [comment]
Closing stale issue, already fixed.
