### ISSUE TITLE
A height fog of some sorts? 

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/base#1113]
Basically some sort of way to have the fog start from the lowest point of a map, and blend in with the rest of the scenario.

![image](https://user-images.githubusercontent.com/24359960/100530328-58a2fd00-31cf-11eb-9c55-cc494a2fa2f4.png)
![image](https://user-images.githubusercontent.com/24359960/100530344-92740380-31cf-11eb-91e5-93f7ae24ea08.png)
![image](https://user-images.githubusercontent.com/24359960/100530368-f3034080-31cf-11eb-9fbc-9d158976fb91.png)

Maybe with two methods, one by using a  material, as in, stripping things off from the water shader, so it just leaves the volumetric fog off it, and one that is a general var for use in the maps.

A perfect candidate for this would be Ubik and Ghost, with it's taller than life buildings.

**Comment by EtchDraws** [comment]
Yes, I believe walking around with fog near your ankles would be a proper addon for any stealth/sniper style maps in the future.

**Comment by q009** [comment]
Available in editor

**Comment by EtchDraws** [comment]
its been four years
I have literally changed careers lol
