### ISSUE TITLE
new cubescript features

### ISSUE THREAD

**Issue by cloudziq** [redeclipse/base#1225]
It would be very useful to have additional functions in cubescript for operations on the selection:
  - the ability to move the selection in any direction (x, y, z), or, if it's too much, just towards the currently selected side of the cube (selorient side)
   - the ability to enlarge the selection by `x` cubes, as above - or just in the direction of the current selection orientation

   - the ability to read the FPS of other players. I know this is debatable and would require consent from a large majority.
     That's why I have another idea that does not reveal the fps value in any way:
     - a command that has two parameters. For example, let it be `(getclientfps A B)`, where `A` is the client's number, ` B` is a boolean (0 or 1)
       When bool is set to `0` - the command would always return 1 (100%), using the command again, but with the value set to `1` instead, would return the percentage difference, for example: `0.6` -which would mean a 40% drop in fps from the previous command use.  Is it possible?

**Comment by Calinou** [comment]
> the ability to read the FPS of other players. I know this is debatable and would require consent from a large majority.
That's why I have another idea that does not reveal the fps value in any way:

I don't think it's *that* debatable, another open source FPS (Xonotic) already allows seeing players' FPS on the scoreboard.

**Comment by IceflowRE** [comment]
>     * the ability to read the FPS of other players. I know this is debatable and would require consent from a large majority.
>       That's why I have another idea that does not reveal the fps value in any way:

This won't help you that much as you do not know the other players graphic settings and resolution.

**Comment by Dziq84** [comment]
other people gfx settings etc are not a problem - I just want the `drawing` scripts to intelligently adjust the speed of geometry operations, so that nobody lose too much fps, so that everyone on the server has a relatively stable framerate.

@Calinou, that's why I have a secondary idea described, so fps are always hidden from each other.
