### ISSUE TITLE
Problems launching from ubuntu CLI

### ISSUE THREAD

**Issue by Xeniatrans** [redeclipse/base#1228]
> ONLY report a feature request if it was already discussed at: https://redeclipse.net/world/issues
> PLEASE search the issues before submitting your own. Be sure to rename your `config.cfg` and check if the problem still occurs.

- Version and build: [v1.6.0] [build]
- Related discussion: redeclipse/world#ID
- Observation: [Screen tearing, refuses input, music and animations play but i have to turn off power to get my laptop to work. only happens in CLI, works fine from GUI]
- Expected result: [That the game would run normally]
- How to reproduce: [launching the game from the command line interface]

```
Insert the contents of your `log.txt` here.
```

**Comment by qreeves** [comment]
SDL without X11 will run in software mode and won't be hardware accelerated. Run from X11 for hardware acceleration. This can't be resolved by Red Eclipse.
