### ISSUE TITLE
Grenades Sticky Mode sometimes will stay in air.

### ISSUE THREAD

**Issue by ghost** [redeclipse/base#1239]
If I throw a grenade in secondly mode to another player, but he has gone away before the grenade attached, the grenade will stay in air before explode.

**Comment by chantianz** [comment]
This bug appears in 2.0.0 Master 2978.

**Comment by Jigoku** [comment]
I would guess it could be related to this old issue: 
https://github.com/redeclipse/base/issues/116

**Comment by qreeves** [comment]
Closing as duplicate of #116
