### ISSUE TITLE
soft particle shading not working correctly

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1244]
This is under the assumption that PT_SOFT is supposed to be blending the particle texture when it intersects with overlapping geometry; for example:   http://blog.wolfire.com/2010/04/Soft-Particles

The particle textures are abruptly clipped off:
![2021-03-12-073007_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/110931755-8a754500-8322-11eb-9bae-081943d4c3b7.png)
`softparticles` has no visible effect when the particlesoft shader is used, which i believe is supposed to be depth testing to factor in alpha blending similar to the wolfire link above.

**Comment by Jigoku** [comment]
So turns out it wasn't the shader, but most particles are using quadrenderer (they need softquadrenderer for it to work):
```diff
diff --git a/src/engine/renderparticles.cpp b/src/engine/renderparticles.cpp
index 5b767e87..04c58827 100644
--- a/src/engine/renderparticles.cpp
+++ b/src/engine/renderparticles.cpp
@@ -1172,7 +1172,7 @@ static partrenderer *parts[] =
     new softquadrenderer("<grey><rotate:1>particles/hint_vert", PT_PART|PT_BRIGHT),
     new quadrenderer("<grey>particles/hint_vert", PT_PART|PT_BRIGHT),
     new softquadrenderer("<grey>particles/smoke", PT_PART|PT_FLIP|PT_SHRINK|PT_WIND),
-    new quadrenderer("<grey>particles/smoke", PT_PART|PT_FLIP|PT_SHRINK|PT_WIND),
+    new softquadrenderer("<grey>particles/smoke", PT_PART|PT_FLIP|PT_SHRINK|PT_WIND),
     new softquadrenderer("<grey>particles/hint", PT_PART|PT_BRIGHT),
     new quadrenderer("<grey>particles/hint", PT_PART|PT_BRIGHT),
     new softquadrenderer("<grey>particles/hint_bold", PT_PART|PT_BRIGHT),
```
![2021-03-12-151435_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/110960173-64619c00-8346-11eb-8e78-8d0a6c8210a4.png)

Wondering if this should be changed to softquad for this smoke particle?

**Comment by qreeves** [comment]
Another one that was fixed accidentally in a recent overhaul 😅
