### ISSUE TITLE
UI / HUD Watchlist / Bug and Wishlist for 2.0.1 Update

### ISSUE THREAD

**Issue by dc-de** [redeclipse/base#1259]
Here are some bugs and wishes on UI and HUD related things I noticed.

1. Wish/Bug - Load background animation und music first and play it while loading the rest, would make it look nicer.
![20210516235942](https://user-images.githubusercontent.com/60038236/118891891-5872f700-b900-11eb-8c25-29d20e07ca87.png)

2. Bug - Playermodel preview can rotated and stick after cursor is leaving the screen area. Possible in menu-Ui and while match.
![20210517000008](https://user-images.githubusercontent.com/60038236/118892005-86583b80-b900-11eb-94b4-0f14a7c4c766.png)
![20210517000526](https://user-images.githubusercontent.com/60038236/118892067-9e2fbf80-b900-11eb-97de-ec74d3e688c5.png)

3. Bug - During loading of submenue entrys like about, accounts etc. main-ui will shown and blinking.
![20210517000146](https://user-images.githubusercontent.com/60038236/118892368-19917100-b901-11eb-8f85-cee1aac7917e.png)

4. Bug - Not a real bug but the year entry in about is 2020, should it be 2021 now?
![20210517000159](https://user-images.githubusercontent.com/60038236/118892534-5198b400-b901-11eb-9d23-56a805bd04cf.png)

5. Bug/Wish - The Demo UI thing... There is now easy way to record Demos and the Option how Demos can replayed is a bit confusing for now players... it might be better to make an separated Demo Play UI and Demo Record UI.
![20210517000308](https://user-images.githubusercontent.com/60038236/118892795-b5bb7800-b901-11eb-899e-300f0375e8d1.png)

6. Bug/Wish - There is no easy way to make a blank new map without a terminal command now as you can see on this screenshot. There should be an button on editing that creates a blank new map and it must be include all accessible content in data with fetching all texture, mapmodel ect.. cfg's to get sure that the player had everything on hand, because unexperienced players often don't now how to add texture, sounds and mapmodels to the map.cfg.
![20210517001342](https://user-images.githubusercontent.com/60038236/118893279-77728880-b902-11eb-978d-d01c9643622a.png)
![20210517000359](https://user-images.githubusercontent.com/60038236/118893352-9244fd00-b902-11eb-8bc9-13b2e8fd0dc8.png)

7. Bug - Empty vanity elements make not much sense and can confuse a player. Empty selections or drop-down should not displayed. (or someone is making a butt vanity will fix that too :D ) 
![20210517000653](https://user-images.githubusercontent.com/60038236/118893651-10a19f00-b903-11eb-8ccb-400927dc7ccd.png)

8. Bug - Reset button I vanity ui will reset / remove default weapon in preview  too! Yeah its only an detail but can confuse a player a bit. I think the default weapon should displayed all the time and not effected by the reset button. Note: this not happens while a match!
![20210517000803](https://user-images.githubusercontent.com/60038236/118893929-8dcd1400-b903-11eb-91fd-d4a79b3207c5.png)
![20210517000805](https://user-images.githubusercontent.com/60038236/118893956-97ef1280-b903-11eb-9917-b5cd5045f7dc.png)

9. Bug/Wish - Setting a white #ffffff or a black #010101 skin color is difficult because the slider will set the on #0000000 to full white to avoid a full black. The slider should limited to the lowest #010101 setting to avoid this strange looking behavior an making color selection a lot easier.
![20210517000823](https://user-images.githubusercontent.com/60038236/118894328-4f842480-b904-11eb-81b9-6d095fdd327d.png)

10. Bug - While Lan connect and other Server connections attempts the minimap and health hud element and other hud elements are displayed for no reasons. They should not visible to the player during this.
![20210517000927](https://user-images.githubusercontent.com/60038236/118894594-d3d6a780-b904-11eb-84fb-88eabda2f87c.png)

11. Bug/Wish - During the time before a match start only sometimes existing spec cams will seleted and shown to the player, very often the spec cam starts on the old way on an randome entite ect. like before cams integrated. (And displaying the mini map while spec cam make not much sense to me but yeah its my personal feeling about this :D )
![20210517001028](https://user-images.githubusercontent.com/60038236/118895124-db4a8080-b905-11eb-8aac-8597b122a792.png)

12. Wish - I miss the option in hud to see all items the player carry with like mines grenades sec weapons rockets ect. like in the old hud in 2.0.0. I also noted that the positioning of the movement cool downs placed not so well. I would be nice to have them all on the left side and the weapons stuff on the right side.
![20210517001053](https://user-images.githubusercontent.com/60038236/118895500-9410bf80-b906-11eb-980f-d7373979786b.png)

13. Wish - Camera Names are a good options but the default cam name is not so interesting I think. The cam name and icon should only displayed if the cam has a different name then the automatic given number. I also think that the player should have an little UI for quick selecting these special named cam like "CAM Alpha Base, CAM Center Yard, ect...".
![20210517001113](https://user-images.githubusercontent.com/60038236/118895877-4cd6fe80-b907-11eb-87ab-276c90735702.png)

14. Bug - If the player dies the scoreboard will interrupt and close every other UI menu ect in front of. Example a player like to vote for an other map while he is alive in game and during this he/she get killed while he/she is making the choice in voting ui, this will cancel his/her attempt there and show eminently the scoreboard. The score board should only displayed if the player had not opened an other ui at the same time when he/she is get killed. Same behavior happens also if a match ends, then the scoreboard would also force to close everything else.
![20210517001223](https://user-images.githubusercontent.com/60038236/118896404-75132d00-b908-11eb-90b2-71fc64da7ca3.png)

15. Wish - If there is now map suggested on current Votes UI there should be a button to quick vote for a map only if there are no other votes. The look better I think and will help a new player a bit to make a vote.
![20210517001302](https://user-images.githubusercontent.com/60038236/118896603-e6eb7680-b908-11eb-9d8d-542d22e76074.png)
![20210517001309](https://user-images.githubusercontent.com/60038236/118896632-f66abf80-b908-11eb-81ce-73c554dd8c84.png)

16. Bug - If the Rest Keybinds is selected a different Keybind setting I set then the default ones. And I also noted that the default Keybinds or old and missing some functions or having old elements like the not working demo-ui ect. And the overview of the actions key is not correct and updated after a reset or a key bind change.
![20210517002112](https://user-images.githubusercontent.com/60038236/118896944-accea480-b909-11eb-9eff-01fc407b730f.png)

17. Bug - I am not sure but switching between ANSI Qwerty and ANSI Dvorak dont make a noticeable difference... I think this is old not longer needed right?
![20210517002332](https://user-images.githubusercontent.com/60038236/118897159-020ab600-b90a-11eb-952b-53ffd90d30af.png)

18. Bug - Very often UI error prompts are incomplete like this... The error messages should show the full path / command if something went wrong. (I am not sure what happened here exactly)
![20210517002421](https://user-images.githubusercontent.com/60038236/118897548-d63c0000-b90a-11eb-83a6-b7618357c20a.png)

19. Bug/Wish - En collectable entity like weapons and on triggers there is not longer a little hint like "press E" like in 2.0.0.
Bringing back a message like this would help new player to know how to pickup weapons or open doors and execute triggers.
![20210517002600](https://user-images.githubusercontent.com/60038236/118897801-4f3b5780-b90b-11eb-8c8a-1aef22343d49.png)
![20210517002629](https://user-images.githubusercontent.com/60038236/118897822-5d897380-b90b-11eb-8383-719afdf08cc2.png)

20. Bug - If the player change a vanity while he is in a match the new vanity could be applied and updated to the player but I cant removed or rested to nothing by using reset while in a match. The reset is also not working if you are not in a match.
![20210517002818](https://user-images.githubusercontent.com/60038236/118897963-beb14700-b90b-11eb-9ad9-a612048128dd.png)

21. Bug - On the Single Player Challenge you can bypass undone levels by selecting and switching between the last two done levels.
![20210517003654](https://user-images.githubusercontent.com/60038236/118898139-28c9ec00-b90c-11eb-8401-01c95ee0bcfc.png)

22. Bug/Wish - Voting for a race map will end up by default in "team race", that's no ideal because ffa race a preffered and make more sense to make this default. race should always the ffa mutator preselected on voting to avoid this and make its more easy for players to use the race/parkour game mode.
![20210517003921](https://user-images.githubusercontent.com/60038236/118898436-d2a97880-b90c-11eb-86e3-f913de9e03ff.png)

23. Bug - Different Window sizes on the voting ui, if you selecting demo or editing the voting window will have a different width. This is not looking good I think, the window size on the same ui should always be the same for astatic.
![20210520014944](https://user-images.githubusercontent.com/60038236/118898990-12bd2b00-b90e-11eb-9579-898fa993240a.png)
![20210520014941](https://user-images.githubusercontent.com/60038236/118898997-15b81b80-b90e-11eb-8fef-bce3867d7f34.png)

24. Wish - the chat and all other messages should be scroll able to make reading and not missing old messages in HUD.
![20210520015445_1](https://user-images.githubusercontent.com/60038236/118899535-392f9600-b90f-11eb-88ec-1e442f26f9ab.jpg)

A long list I know but I yeah I will not be dc if I don't make a long list like this. :D

**Comment by qreeves** [comment]
Wow, lots of effort put into this. Well done!

**Comment by dc-de** [comment]
Yeah, but I diced to not review the edit UI at this point and waiter after Q009 finish it.
I literately test every option and possibility selection on the UI in game for this. :D

**Comment by dc-de** [comment]
New UI is out, this list is no longer needed.
