### ISSUE TITLE
Players' legs movement is strange when moving left and right.

### ISSUE THREAD

**Issue by cantianz** [redeclipse/base#1292]
Happened in master 2978 2.0.0.

https://user-images.githubusercontent.com/87136890/128690585-ccf76741-40c7-42d9-998d-11e1ff033581.mp4

**Comment by Calinou** [comment]
It looks as expected; the animations were always made this way. It's not very realistic, but it makes sense in a video game context.

**Comment by cantianz** [comment]
Will not fix it?

**Comment by SniperGoth** [comment]
It has more to do with the animation more than anything else.
Making a new animation for strafing would probably be the best approach, where both legs don't collide with each other when you switch from left to right.

**Comment by qreeves** [comment]
It's not a bug, discussions go here: https://github.com/redeclipse/base/discussions

**Comment by cantianz** [comment]
> It has more to do with the animation more than anything else.
> Making a new animation for strafing would probably be the best approach, where both legs don't collide with each other when you switch from left to right.



> It has more to do with the animation more than anything else.
> Making a new animation for strafing would probably be the best approach, where both legs don't collide with each other when you switch from left to right.

This answer is useful than others.
