### ISSUE TITLE
Map shadows will disappear in large maps.

### ISSUE THREAD

**Issue by cantianz** [redeclipse/base#1293]
When using rifle's scope to zoom in, shadows will disappear. I have asked this problem in discussions #1279 .dziq siad it is Engine limitations, or buggy zoom code.

**Comment by Calinou** [comment]
This is expected due to how real-time directional light shadows work in game engines.

**Comment by cantianz** [comment]
Why close this issue? It is a bug.

**Comment by qreeves** [comment]
It is intended behaviour of the engine and entirely performance based, there are settings already to increase the shadow distance but it requires very good hardware.
