### ISSUE TITLE
Fortitude "-$1m" bug

### ISSUE THREAD

**Issue by dc-redeclipse** [redeclipse/base#1320]
### Discussed in https://github.com/redeclipse/base/discussions/1255

<div type='discussions-op-text'>

<sup>Originally posted by **dc-de** May  5, 2021</sup>
`Fortitude` is a official Red Eclipse map made by James 'Max Payne' Tonjes, port by Alex 'molexted' Foster and is official included in map rotation since Red Eclipse 2 version 2.0.0.
To keep this map updated and fitting to the game I will take of it updating it to fit any new Red Eclipse version,

**Fortitude** (New Version for Red Eclipse v2.0.1)
![fortitude](https://user-images.githubusercontent.com/60038236/117155413-0b017080-adbd-11eb-9976-e8d50053229f.png)

_Steps I done for the update:_
- fixed blocks
- many many texture fixed and improved some places to look better and always a lot off error correction
- improved all light ents
- fixed clip issues and add more no parkourmaterial
- add rails and cameras
- improved all bot waypoints
- fixed sounds playerstart positions
- improved environment vars
- and many other fixes of existing errors from the past versions

... all and all try too make it looking good to fit with all the other cool new maps in 2.0.1.

**Current Version**
**_RE 2.0.1_**
**current latest version = r863**
[fortitude-r863.zip](https://github.com/redeclipse/base/files/6427803/fortitude-r863.zip)

**Bugs:**
1. bug discovered: this map had the unsafe normalization rail bug!
2. bug discovered: this map had the bot rail collision bug!

How to reproduce the bug (example purge):
[https://youtu.be/ZIKb1Oprpx0](https://youtu.be/ZIKb1Oprpx0)

If this bug is not fixable or worth it to fix, just remove the map from rotation, its then quit sad because of that many hours updating it but game must be run stable.

**Comment by q009** [comment]
Fixed
