### ISSUE TITLE
particle quality not saving

### ISSUE THREAD

**Issue by nochinator** [redeclipse/base#1346]
- Version and build: steam
- Observation: particle quality setting resets to high sometimes when restarting the game, and always when restarting the system
- Expected result: map effects setting to save
- How to reproduce: change the map effects setting, restart the system, check the setting it is back on high, this works for both windows and ubuntu, mac untested

other notes: this is a small error/annoyance for those that use older systems that can not use high settings (like me)

EDIT: fixed particle quality to map effects

**Comment by qreeves** [comment]
I am unable to locate a setting for "particle quality" in the settings UI, only "soft particles" and "move with wind". Please advise where you are changing this setting. Is it the UI, or are you using variables?

**Comment by nochinator** [comment]
my bad I meant map effects. sorry

**Comment by qreeves** [comment]
I have located the problem regarding this issue and the setting is indeed not saved in the configuration file. I am pushing a fix upstream but this will not be available in the stable version of the game until the next release.

You may either:
- Switch to the development version: `Right click game in Steam library > Properties > Betas > "devel"`; or
- Add `mapeffects 1` to your *autoexec.cfg* (location [depends on operating system](https://www.redeclipse.net/docs/FAQ#where-do-i-find-screenshots-logs-and-other-user-data)).

Thank you for taking the time to report this issue. Please accept my apologies for the inconvenience.
