### ISSUE TITLE
Game pulls you out of the main menu roughly 5 seconds after death

### ISSUE THREAD

**Issue by MirceaKitsune** [redeclipse/base#1372]
- Version and build: Git master, currently at 5ae71ee6fb3f0bd930f02df119eb645c5189fd12
- Observation: If you open the main menu immediately after you die and before respawning, the menu will be forcefully closed on you roughly 5 seconds after you died which can be very annoying. This seems to occur when the death screen switches to showing the scoreboard and allows you to respawn.
- Expected result: The game shouldn't automatically pull you out of the main menu under any circumstance, you should remain there until you choose to close it and return to the world.
- How to reproduce: Be killed during a match. Right after you're dead, press esc to open the main menu, go into settings to tweak something for example. Roughly 5 seconds in, the main menu is suddenly closed on you for no apparent reason.

**Comment by MirceaKitsune** [comment]
I should have probably mentioned the endgame issue as well, thought they're the same thing initially: When the game ends, if you open the main menu during the first seconds, you're once more pulled out when the map voting screen shows. At least the death issue is fixed though, just noting this one too if it can be resolved as easily later.

**Comment by dc-de** [comment]
thats a kown bug should be fixed while overhauling the ui's
