### ISSUE TITLE
No chat in edit mode

### ISSUE THREAD

**Issue by MirceaKitsune** [redeclipse/base#1374]
This issue was brought to my attention by someone else during a collaborative map editing session. It's currently not possible for people to use or see the chat during edit mode: If you wish to say something or even see what someone else said, you need to press F2 to spawn as a player then F2 again to return to edit mode. While this limitation may make sense in keeping the interface clean and the chat key free for other uses, it can make communication difficult as it requires interrupting your work to access the chat: If lifting it can be possible, I would to suggest allowing the chat system to work identically when a player is in the editor interface.

**Comment by dc-de** [comment]
I was that one lol. I was wrong, just a rebinding of `chat` to key does the trick.
![20221023_202129](https://user-images.githubusercontent.com/60038236/197415745-194e5ca8-417a-43e2-8004-bdfdd1ab0f22.png)
So this can be closed now so far.
For the future should maybe console / chat binding be included in the edit ui keybinding menu.
In general we should keep key binding as easy as possible, I think this will be improved while the menus getting updated and overhauled.

**Comment by MirceaKitsune** [comment]
Was gonna close but latest dev doesn't work on its own yet, probably requires the change in the screenshot: T and Enter both open chat in player mode but not in edit. I figured it might be a simple keybind issue since that shouldn't be a conflict between the two modes, glad it won't be a difficult one to get past.

**Comment by dc-de** [comment]
As I mention you have to rebind it once baucause of the occupation from the edit ui.
Just go Settings -> key Binds and bind `chat` under edit bind to that key you like and its working again.
This is the current state for the dev version and it will be no longer nescerry in the final release.

**Comment by MirceaKitsune** [comment]
Awesome, that solved it for me. Closing this then.
