### ISSUE TITLE
Teleporters have extra range past the sphere represending radius visually

### ISSUE THREAD

**Issue by MirceaKitsune** [redeclipse/base#1380]
- Version and build: Git master
- Observation: When a teleporter is placed against a two-sided wall, and its radius is adjusted precisely as to not surpass that wall, the player will still be teleported when touching the back side of the wall. Either the visual sphere in edit mode is smaller than it should be drawn, or collision detection for teleporters (possibly also triggers and similar) is larger than it should be.
- Expected result: The mapper expects the player to be teleported once a piece of their bounding box intersects the radius sphere seen on the teleporter. This isn't what's happening since the player isn't walking through the wall to be able to get that close, teleporters must thus have some extra range added to them.
- How to reproduce: Create a wall of any thickness. Put a teleporter on either side of it. Set its range so that the green sphere barely touches the other side of the wall but not quite. Now spawn as a player and push into this other side of the wall. You should notice the player teleporting, even if the entity's sphere is equal or smaller to the wall face.

The screenshots below are the setup I noticed this with, though I since changed the teleporters on my map for unrelated reasons. The player would get teleported while walking through the lateral hallway if they got close to the wall, even when I shrunk the radius to be about halfway through it.

![20221012_184500](https://user-images.githubusercontent.com/825418/197417821-a895244a-9287-4f45-a1e8-85f48b7e6289.png)
![20221012_194712](https://user-images.githubusercontent.com/825418/197417823-6c654ba9-5541-441b-b5b0-02ae4ed32475.png)

**Comment by dc-de** [comment]
the wall size is to small and teleports are not designed to use them in that way.
A common place for teleports are most the edges and endings of a map.
Putting it in the center with that small size of a wall can only leading to that behavior.
To solve this just increase the wall thikness till the beahavior stops.

**Comment by MirceaKitsune** [comment]
Increasing the size of the wall did solve it on my map. The reason I was reluctant to shrink the teleporter radius instead is that also scales the visual portal and made it too small, perhaps it should be a separate variable? It still feels like a bug that teleporters exceed the sphere radius, but if that's normal I don't mind now that I know.

**Comment by dc-de** [comment]
placing of portals straight on wall is also not recommanded it leads to all sort of behavior like that. Wall thickness and the position should be carefully chosen. A good working example how the new teleports should be used are on the latest version map bloodlust.

**Comment by MirceaKitsune** [comment]
I already had it offset by one grid unit from the wall, the portal would Z-fight with the wall surface if directly on it. Mine is closer than in Bloodlust but now it seems to work fine. Closing this then.
