### ISSUE TITLE
Inifinite fullscreen to window & back loop. 

### ISSUE THREAD

**Issue by Sondro** [redeclipse/base#1386]
Graphics card: NVIDIA Corporation GM200 [GeForce GTX 980 Ti]
OS: Debian Bullseye

There's some sort of pretty serious bug from 1.6+ that also effects the Neothyne Engine (which I assume is where the behavior originated).

Basically, the UI is nearly unusable from constantly shifting position & fullscreen changing rapidly in an endless loop. 

I've never had any problems setting the UI to fullscreen in any other game or app (I think this bug may be caused by having a multiple monitor setup, but I haven't looked too deep into it).

I created a fix that allows fullscreen to work perfect for me by just maximizing & restoring on fullscreen fail here: https://github.com/redeclipse/base/commit/320f49d80ba469dbf5e05bd72ba2c8e20db343f2

**Comment by qreeves** [comment]
Maximizing a window is not the same as setting fullscreen. The proposed solution breaks fullscreen completely. It is highly suspected there is a deeper problem that is unique to your system. Without any way to verify or test the problem we are unable to address the issue.

**Comment by Sondro** [comment]
I know maximizing is not the same as fullscreen -- my 'solution' will only maximize in the case that fullscreen FAILS.

Fullscreen works in this example & there is no endless loop like behavior.

**Comment by dc-de** [comment]
Can you provide us with information about your screen resolution?

**Comment by qreeves** [comment]
The proposed solution breaks compatibility with retina/super-resolution displays. If the code in question results in an infinite loop, it is likely that your window manager is not cooperating. I can't push random fixes without knowing the underlying cause.

**Comment by Sondro** [comment]
IceWM 3.2.2 with 2 1080p screens.
