### ISSUE TITLE
Weapon dynamic lights stop appearing if they only touch models (such as players), but no world geometry

### ISSUE THREAD

**Issue by Calinou** [redeclipse/base#1414]
- Version and build: Git feaf1c44d17d1d09b0bb171a78c1c6ce63bdeb06 (I could reproduce this at least a few months ago too)
- Related discussion: N/A
- Observation: Weapon dynamic lights stop appearing if they only touch models (such as players), but no world geometry. I assume this happens because the engine optimizes away the light, since there is no world geometry touching the light.
- Expected result: Dynamic light should not disappear if it's only touching models (such as a player), as it should still be logically visible in this condition.
- How to reproduce: Hold a weapon that emits a dynamic light (flamer or zapper), then jump while looking down and crouching. You can also crouch, then look down and back up until the light pops in and out depending on its radius.

Video of this occurring:

[simplescreenrecorder-2023-02-17_01.03.51.mp4.zip](https://github.com/redeclipse/base/files/10761938/simplescreenrecorder-2023-02-17_01.03.51.mp4.zip)

**Comment by q009** [comment]
Fixed
