### ISSUE TITLE
Crouch animations are not used for forced crouching when the ceiling is too low

### ISSUE THREAD

**Issue by Calinou** [redeclipse/base#1424]
- Version and build: Git https://github.com/redeclipse/base/commit/a8d924e19a7753029dfaec22083ea0bf10fc5683
- Related discussion: N/A
- Observation: When crouching under an area that is too low to fit standing, the player will remain crouched. However, the standing animation will play in both first-person and third-person. This causes your legs to phase through your body in first-person.
- Expected result: Crouching animations should always be used to match the crouched view height, even if crouching is currently forced due to the ceiling being low.
- How to reproduce: Create a room that is 5 units tall (= 5 cubes in gridpower 2), crouch under it and release the crouch key.

![Releasing crouch key below low ceiling](https://github.com/redeclipse/base/assets/180032/a2c1c4d6-253d-4260-ab99-be5e195119ab)

**Comment by qreeves** [comment]
Fixed in [df7880e](https://github.com/redeclipse/base/commit/df7880e2b5807f4b7e57fee21be7aae7aca24a10)
