### ISSUE TITLE
Point limit not displayed in the scoreboard

### ISSUE THREAD

**Issue by MirceaKitsune** [redeclipse/base#1440]
The new menu and its scoreboard / ready panels don't display the point limit if one is set, only the time limit. If using settings such as `pointlimit 100` or `fraglimit 50` it does not display the amount of score needed to end the match for that particular game mode. The opposite is also true as you can set a score limit without a time limit, the score board should only show whichever is enabled and if both are configured display something like "3:24 minutes or 15 frags left".

**Comment by q009** [comment]
Solved in new scoreboard
