### ISSUE TITLE
show team objective in gauntlet and attack-bb

### ISSUE THREAD

**Issue by bonifarz** [redeclipse/base#145]
When joining a team in _gauntlet-race_ or _attack-bomber-ball_, it would be nice to have an on-screen notification about the objective or role of your team: _Attackers_, _racers_ or _defenders_, possibly in brackets after each team name? Currently, blue races in gauntlet and defends in attack-bomber-ball. Maybe it is more consistent to have blue as defenders in gauntlet, too.

**Comment by q009** [comment]
Done
