### ISSUE TITLE
Acid_Weapon_Model

### ISSUE THREAD

**Issue by Rabidbutton** [redeclipse/base#1450]
New weapon type.

Initial gameplay concept:

Primary fire -> Paintball style projectile, splashes with area of effect, stains surfaces with dangerous acid. 
Secondary fire -> Acid hose, stains surfaces with dangerous acid.
Acid residual -> Damage over time, builds up with acid contact to a limit, fades out.

**Comment by Rabidbutton** [comment]
[Acid_Weapon_Files.zip](https://github.com/redeclipse/base/files/13463181/Acid_Weapon_Files.zip)

**Comment by MirceaKitsune** [comment]
Firstly, thank you again for another beautiful weapon model! Initially I thought this was going to be a new model for the shotgun: Was a bit thrown off to hear we're getting a new gun, I felt we got the right number and adding more now might be complicated... as a final addition to the loadout though I believe this is a most welcome gun and am eager to see it!

There's one final change I'd still make if you can consider it please: Add a glass window to the side showing the fluid in the weapon. It doesn't necessarily need to be a transparent material, though if you feel like modeling the tank's inside that might look really neat... it can be done as just a special shader that simulates a wobbling fluid on part of the surface. I just feel this would make it even better themed and clearer what its purpose is, it looks great regardless.

**Comment by qreeves** [comment]
Completed: see Corroder.
