### ISSUE TITLE
Keyboard layouts are not properly handled

### ISSUE THREAD

**Issue by rachelambda** [redeclipse/base#1562]
- Version and build: steam 723

- Observation: 
Default binds are wrong when using e.g DVORAK, as it uses the same keys as QWERTY would
I am unable to bind "å" key of my keyboard (which would be the W key on qwerty)

- Expected result:
I would expect the game to use keycodes to represent binds, only use keysyms to display the bound keys depending on selected keyboard layout.

This would solve both issues as the default binds would not depend on what layout you are using, and it would not matter what character a given key represents when creating binds.

- How to reproduce: install the game on steam and launch with a non-qwerty keyboard layout

Hope to be able to see this fixed :)

**Comment by qreeves** [comment]
Our keymap resides in `config/keymap.cfg`. Please feel free to contribute keymaps for your own device.
