### ISSUE TITLE
Latest Linux master binary doesn't launch without libsteam_api.so

### ISSUE THREAD

**Issue by user1-github** [redeclipse/base#1607]
I've downloaded the latest Linux master binary from the deploy repo, but it doesn't launch due to the following error:

> redeclipse_linux: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

Maybe there is some launch argument that lets the binary run without Steam?

**Comment by Jigoku** [comment]
Hi. You need to run the shell scripts in that directory to launch the game, as it requires the LD_PATH's and some other vars to be exported at launch

Try running `./redeclipse.sh`

Hope that helps!

**Comment by user1-github** [comment]
> Hi. You need to run the shell scripts in that directory to launch the game, as it requires the LD_PATH's and some other vars to be exported at launch
> 
> Try running `./redeclipse.sh`
> 
> Hope that helps!

Thanks. Yeah I tried launching redeclipse.sh, but now it works because I didn't realize the base repo already includes the steam and discord dependency, so I just had to copy them to bin/amd64 dir that I downloaded from the deploy repo.

On another note, I'm curious why is the Steam dependency required even when launching the game without Steam?

**Comment by Jigoku** [comment]
As far as i know it's just looking for the shared library to detect if steam is installed on the system. If you wanted no steam at all you can build the game with `WANT_STEAM=0` as a make option and it will skip that entirely.

**Comment by Calinou** [comment]
> Hi. You need to run the shell scripts in that directory to launch the game, as it requires the LD_PATH's and some other vars to be exported at launch

If the Red Eclipse binaries are compiled with the correct `RPATH`, setting `LD_LIBRARY_PATH` shouldn't be necessary.
