### ISSUE TITLE
RE (stable) doesnt update win registry

### ISSUE THREAD

**Issue by IceflowRE** [redeclipse/base#182]
Just wanted to point out that RE (stable version) does not update the Windows registry, the official version is "1.5.1" but the display Programs and Features shows still 1.5 .

**Comment by freezurbern** [comment]
While recreating the Windows installer, I thought about this. I believe next major release we should use 1.6.x in the programs and features reg entries, so that there is less confusion. At the moment, this issue is caused by the fact that the upgrade from 1.5 to 1.5.1 is not through an installer (Unless the installer files werent updated for 1.5.1, which they probably should be but that's a hassle too.)

This issue spawns another issue: Updating the installer versions based on the other place the version info is put.

**Comment by bonifarz** [comment]
Calling it 1.5 or 1.5.x does not make a big difference, does it? At least, it is not labeled as 1.5.0.

**Comment by shirepirate** [comment]
the batch updater script can modify the registry easy enough,

`reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Red Eclipse" /v DisplayVersion /t REG_SZ /d 1.5.X`

the trickier part would be telling it what version to update with

**Comment by freezurbern** [comment]
I have written the code for this, but I do not know how to integrate it into the update.bat file. Here's the code snippet:

```

@echo off
setlocal enabledelayedexpansion
@setlocal enableextensions
@cd /d "%~dp0"
rem ==============================

set count=4
for /f "tokens=3" %%a in (..\src\version.h) do (
	if !count! GTR 0 (
		set /A count-=1
		echo %%a
		set RE_VERSION=%%a
		set RE_VERSION=!RE_VERSION:"=!
	)
)
reg query "HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Red Eclipse" /v DisplayVersion
	IF NOT ERRORLEVEL 1 (
		reg add "HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Red Eclipse" /f /v "DisplayVersion" /t REG_SZ /d %RE_VERSION%
	) ELSE (
		reg query "HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Red Eclipse" /v DisplayVersion
			IF NOT ERRORLEVEL 1 (
				reg add "HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Red Eclipse" /f /v DisplayVersion /t REG_SZ /d %RE_VERSION%
			) ELSE (
				echo Uninstall information not found.
			)
	)

```
Right now, it polls version.h and grabs the information from there, so it would need to be run after the src/ folder is unpacked/updated. I hope this is useful to someone.

**Comment by qreeves** [comment]
If you're going to `reg` on `HKLM`, then you're going to need administrator. Which means you'll need to add it to `update.bat` as insertions into the `install.bat` file.

**Comment by qreeves** [comment]
No longer applicable.
