### ISSUE TITLE
Give routes in race colours

### ISSUE THREAD

**Issue by JeffBobbo** [redeclipse/base#315]
Colours can probably be implemented the same way as colours (#314).

Colours gives quick feed back to the user about which route is harder, also opens up the possibility, if someone wanted it, to render all routes at once without it becoming confusing.

The general trend seems to be the higher the number the more difficult/advanced the route is, it could be a simple interpolation from the highest route and 0 through colours (like green to red). Or we could give the ability to pick colours.

**Comment by shirepirate** [comment]
a simple /routename through /routename3 & /routecolour through /routecolour3 will probably suffice (as world variables). if you make it too complicated it is no longer helpful to those that would need it

**Comment by qreeves** [comment]
These would be better as world aliases actually, so it can support an unlimited number. As I mentioned in the other thread I accidentally bumped: `route_N = [name]`

**Comment by shirepirate** [comment]
is that an entity attribute though? or are world aliases something else

**Comment by qreeves** [comment]
World aliases are the same as normal aliases, except they are saved with the map. It allows you to set up scripted triggers (`on_trigger_N`), defend point names (`point_N`), and whatever else you might need an alias for in a map context.

**Comment by bonifarz** [comment]
Agreed, this might go well along with route names #314.
Just to clarify, right now routecolour is a client side option and we have a button for it in the help menu (race mode only)
