### ISSUE TITLE
Updater script shows 100% while downloading packages

### ISSUE THREAD

**Issue by freezurbern** [redeclipse/base#437]
![screenshot](https://cloud.githubusercontent.com/assets/6363417/12419115/f8042d18-be81-11e5-92ab-11af6fee9bd0.png)
The update script shows the ############## 100% line even while downloading. It'd be more clear if this moved from 0 to 100 instead of starting and staying at 100%. The 'cursor' or something that highlights characters flashes across the line of #########'s and that's the only indication that something is happening. This happens on both Windows 7 and Ubuntu for me. It used to move across but something changed a couple months ago.
Needs verifying. Thanks.

**Comment by shirepirate** [comment]
it only appears that way because it restarts for every file it downloads, and some files are pretty small

**Comment by freezurbern** [comment]
For example the maps file is giant compared to others, but shows 100% the
entire time.

**Comment by zaquest** [comment]
it's because github.com doesnt always send content-length header, they probably simultaneously create tarball and stream it to user.

**Comment by shirepirate** [comment]
does not affect me on Windows:

![mwsnap0032 2016-01-19 19_24_44](https://cloud.githubusercontent.com/assets/2275004/12436436/503fa62c-bee3-11e5-9cce-16deb73ca591.png)
![mwsnap0033 2016-01-19 19_24_47](https://cloud.githubusercontent.com/assets/2275004/12436437/56f93eba-bee3-11e5-9b14-1d9cb327ad87.png)

**Comment by freezurbern** [comment]
![no-num-bar](https://cloud.githubusercontent.com/assets/6363417/12436633/05db9a08-bee5-11e5-80cb-2ee7b2efc73b.png)
Not sure what I did different. To test, I downloaded the base-stable.zip and ran redeclipse.bat. Now I don't get a ########## line at all. Instead just some numbers.

**Comment by qreeves** [comment]
> it's because github.com doesnt always send content-length header, they probably simultaneously create tarball and stream it to user.

Precisely. Usually only happens the first time the file is requested (or if it hasn't been requested for a while and is removed from their cache).

> Not sure what I did different. To test, I downloaded the base-stable.zip and ran redeclipse.bat. Now I don't get a ########## line at all. Instead just some numbers.

I was using a different output style, but it doesn't show the correct totals either. There's another output style that shows it in a set of sequential bars each totalling a specific length. I tried piping this into a function to print a dot every line but I wasn't really happy with it either.

There's not much we can really do about this other than change the way the information we have is presented.

**Comment by q009** [comment]
Updater script no longer in use
