### ISSUE TITLE
rotation of player preview

### ISSUE THREAD

**Issue by bonifarz** [redeclipse/base#44]
With even more vanity items to explore, it would be cool to have some control of the player preview's rotation (at least for the larger one, "playerprev"). Pausing the rotation does already help much to look at vanity items, so what about a more convenient way than messing with /gamespeed or /gamepaused? An interactive way to rotate the preview model would be a very nice extra.

**Comment by Jigoku** [comment]
Feature was added in https://github.com/redeclipse/base/commit/23be4849f2269a1b463c943cd84cbcdd39da5b2d
