### ISSUE TITLE
Windows updater requires MSVC runtime

### ISSUE THREAD

**Issue by qreeves** [redeclipse/base#451]
Trying to run the updater section on newly installed systems results in a `msvcr100.dll` not found. It should be identified what part is asking for this (curl or elevate) and a resolution should be found, preferably one that doesn't require us to distribute the runtime.

**Comment by acz13** [comment]
What Windows installer/updater does RE use? I've always used git so...

**Comment by acz13** [comment]
Worst comes to worst msvcr100.dll isn't a hard file to find.

**Comment by shacknetisp** [comment]
Curl is the program requiring `MSVCR100.dll`.

**Comment by IceflowRE** [comment]
Use wget for windows?
https://eternallybored.org/misc/wget/

**Comment by qreeves** [comment]
*curl* replaced/displaced *wget* (first few revisions of the updater I wrote did actually use wget). It's OK though, we can find and/or make our own version compiled with MingW instead of Visual Studio/etc.

**Comment by qreeves** [comment]
Updater is deprecated and the cause of this has been removed.
