### ISSUE TITLE
Icons for entities in editing

### ISSUE THREAD

**Issue by IceflowRE** [redeclipse/base#51]
At the moment you have small purple light circles for checkpoints, lights ... (all newents ...). I see octaforge and there the light have "big" icons with a lamp. It would be nice if RE can get something like this too. So all is better to see and to find. (extra: Option to switch btw icons and purple lights)

**Comment by shirepirate** [comment]
i seem to remember reading somewhere the purple dot was chosen because of it's non-obtrusiveness, yet it still stands out enough that you can find what you're looking for. then there's always the findent command of course. so what, specifically, are you suggesting be used instead of the purple dot? give an example

**Comment by IceflowRE** [comment]
Like i write above an icon with an grey bulb for light like in octaforge or an an abstract fire for fire particle. And beacause of the the non obtrusiveness i want an option to switch, and the icons because i dont want every time searching, its faster without.
Here you can see the light icon: http://i.imgur.com/Ce2Hj.jpg

**Comment by ZeroKnight** [comment]
That would be pretty cool actually. As long as you keep the icons small (maybe with an option to toggle between them and the purple dots as suggested), and maybe even a bit transparent they should remain unobtrusive while still being easier to spot, on top of being able to identify various entities at a glance.

**Comment by shirepirate** [comment]
all right, we'll probably need to see some high quality example icons to see if it could work

**Comment by qreeves** [comment]
For future reference, suggestions like this should go through the forums first. @IceflowRE is flooding the issue tracker without discussing with the community first. The issue tracker is for confirmed/approved items only. It is not a free for all suggestion box. We need to be able to review issues without all the clutter.

**Comment by IceflowRE** [comment]
Urgh yeah my fault, but only the last two issues. I will correct it.

**Comment by acerspyro** [comment]
*raises hand* I can make some vector icons.

**Comment by qreeves** [comment]
@acerspyro Iceflower has already been working on this, so you will want to coordinate with them.

**Comment by bonifarz** [comment]
Some of his work is here: https://github.com/red-eclipse/community/tree/master/Iceflower/textures/Edit%20Icons

**Comment by IceflowRE** [comment]
Better look here because here is a little bit more (Google Drive): https://drive.google.com/open?id=0B__JdfXlvXlxWVFkOTVhamx1TGs&authuser=0

**Comment by IceflowRE** [comment]
false button D:

**Comment by qreeves** [comment]
I'll write the code for this when I next get a chance.

**Comment by Dziq84** [comment]
Much sorry for this bump, this is already closed but I have an idea for light icons, maybe good idea is to make them dynamically coloured, so these might reflect actual light color (for example: green light= green) ?

**Comment by IceflowRE** [comment]
Hi, Dziq84 this topic is NOT closed and dynamical colouring should be possible ingame.

**Comment by q009** [comment]
Done
