### ISSUE TITLE
More obvious guidance for affinity holders

### ISSUE THREAD

**Issue by qreeves** [redeclipse/base#561]
Currently, we rely on a small blip on the radar to guide us to our appropriate goal when carrying an affinity (flag, etc). A periodic "trail" effect coupled to the waypoint system would more accurately guide a player to the destination.

**Comment by freezurbern** [comment]
An idea to add to this: Since the waypoints paths are not smooth, perhaps a smoothing could be applied to the 'trail'. This would make it easier to follow (so your eyes aren't darting all over following each and every little turn the waypoints make)

**Comment by JeffBobbo** [comment]
In the first Halo, when you got lost or there was a new objective for a mission, a compass arrow would appear (like we have in RE), when you were looking in the direction of the objective (even if it was obscured by a wall) the arrow would change into a way point marker like this:
![image](https://user-images.githubusercontent.com/5425481/33080606-744fabe4-ced0-11e7-9772-b7bb2f686cac.png)

This'd probably be better than drawing sketchy lines on the waypoint map. It's similar to what other games do so is clear to players and stands out more than the normal compass.

**Comment by q009** [comment]
Implemented with dyn UIs
