### ISSUE TITLE
Cooking sounds occasionally keep repeating even after cooking is finished.

### ISSUE THREAD

**Issue by shacknetisp** [redeclipse/base#585]
I first noticed this in 1.5.3, but it may have been occurring in earlier versions.
I can't reliably reproduce it, but it happens around once per game where I am cooking plasma2 or a grenade and the cooking sound continues in the background even after I fire. Sometimes dying/respawning will stop the sound, other times it will continue even after respawn. I don't think I've ever heard it caused by someone else's cooking, just my own.

**Comment by qreeves** [comment]
Yeah, I've heard this as well but I didn't figure out what it was I was hearing. Cooking sounds about right.

**Comment by acz13** [comment]
Huh, I've never heard this,  
do you have a demo?

**Comment by shacknetisp** [comment]
On the second grenade throw I managed to get a faint repeating.

[repeating_cook.dmo](http://beha.zapto.org/files/demos/repeating_cook.dmo)

**Comment by qreeves** [comment]
You can use "showgui cursounds" to see information about currently playing sounds.

**Comment by acz13** [comment]
Maybe I didn't catch it but cursounds isn't showing any repeating cooking  
Probably need to rewatch

**Comment by q009** [comment]
Issue not occurring after OpenAL implementation
