### ISSUE TITLE
Alt-tabbing in edit mode triggers grid aid on Linux

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#711]
Tested in Red Eclipse 1.5.8 nix64 on KDE Neon, alt-tabbing out of the game causes the grid aid to be cycled, as the game detects that the tab key has been pressed. This is especially annoying on Linux, where the brush grid causes massive drops in performance as low as 3 FPS on big maps.

A simple fix would be to not trigger any keybinds if alt and tab are pressed simultaneously.
A more involved fix that would solve all bugs of the sort would be to fetch the list of globally defined shortcuts from the DE's API and ignore them in-game to prevent conflicts.

**Comment by TheAssassin** [comment]
> Tested in Red Eclipse 1.5.8 nix64 on KDE Neon, alt-tabbing out of the game causes the grid aid to be cycled, as the game detects that the tab key has been pressed. This is especially annoying on Linux, where the brush grid causes massive drops in performance as low as 3 FPS on big maps.

Wow, another 4 FPS bug victim. I'm affected by a similar bug. The difference is that it is not limited to the edit mode.

How did you find out that it was the grid? I'd like to see your check to see whether I'm affected by the same bug. Then I might be able to develop a fix.

> A more involved fix that would solve all bugs of the sort would be to fetch the list of globally defined shortcuts from the DE's API and ignore them in-game to prevent conflicts.

While this might be true (although ignoring is not the right way, you'd have to ask the user to re-bind the in-game stuff), this is **extremely hard** to do right for all DEs. I've recently started to work on a library that simplifies DE related tasks by providing a common, "magic" API called [libdesktopenvironments](https://github.com/TheAssassin/libdesktopenvironments). Please have a look at the [source code](https://github.com/TheAssassin/libdesktopenvironments/tree/master/src), and you'll see how annoying that can be.

**Comment by acerspyro** [comment]
@TheAssassin I'm 100% sure it is the grid aid, the framerate drop only occurs when it is shown. The bigger the map, the bigger the framerate drop. If I alt-tab out and it goes from the paste aid mode to the brush aid mode (hence alt-tabbing out and leaving the game running with the "4 fps bug"), it goes as far as to create a huge negative impact on the general system performance. FX-8320, 8 GB RAM

May I also add that enabling the edit grid without any antialiasing also causes a huge performance drop (once again, the more surface it has to draw, the bigger the lag). Enabling at least 2x antialiasing solves it 100%.

**Comment by TheAssassin** [comment]
> it goes as far as to create a huge negative impact on the general system performance

That occurs to me too, and it appears as the issue reduces both graphical and overall system performance drastically.

Does disabling the grid help?

**Comment by acerspyro** [comment]
Of course disabling the edit grid helps.

**Comment by molexted** [comment]
acerspyro is talking about #614, the performance issues with the cursor grid and selection grid in edit mode (that's what the editing view menu describes them as)

![20170727163919](https://user-images.githubusercontent.com/23445929/28696442-6c83f10a-72ea-11e7-9373-7c5bb4e2dd25.png)
(14 fps)

**Comment by TheAssassin** [comment]
I've found that my problems are induced by something different, it's the compositor. I'll file an issue as soon as I have more information.

**Comment by TheAssassin** [comment]
See #712.

**Comment by acerspyro** [comment]
No longer an issue since the Tesseract port. See https://github.com/red-eclipse/base/issues/614

**Comment by acerspyro** [comment]
Actually, I noticed that the discussion derived from the original point of this issue, which was that the game would recognise both the alt and the tab being pressed when alt-tabbing.

The alt being recognised by the game is a non-issue, but the game should discard the "tab" button when it is detected with the alt modifier, as it is a standard system shortcut on most platforms and will be used often.

The most efficient way to approach this issue is with a CubeScript variable that identifies a Key+Modifier combination that should not be recognised by the game, similar to this:

`/ignoremodkey L_ALT TAB`

Off the top of my head, other shortcuts that should be ignored:

> Alt + Shift + Tab
> Alt + Space / Alt + F3 (maybe?)
> Super + Anything
> Ctrl + Alt + Delete
> Ctrl + Shift + Esc

On top of this, the alt sometimes gets stuck in the down position after alt tabbing back into the game (on Linux at least). This has the effect of toggling full screen whenever you press the `Enter` key until you push on the alt key again.

The performance issue with the edit grid is gone, however.

**Comment by q009** [comment]
No longer relevant, as tab has a different function now
