### ISSUE TITLE
Avoid spawning multiple players in the same spot

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#722]
This is a problem in games like Duel where two players would spawn on the same playerstart.

Additionally, we could use Quake's tactic and have players spawn at the playerstart that is the furthest away from as many people as possible on top of avoiding the same playerstart.

The first is pretty much a low-hanging fruit, but the second would be nice as well.

This is both a bug and a feature request. The first point definitively needs to be fixed.

**Comment by shirepirate** [comment]
there are options in the entities for mutator-specific ones. but I recall finding out that this was broken when i tried to fix the duel maps near the release of 1.5. i don't know if they are working correctly now

**Comment by qreeves** [comment]
A bug was identified in the spawn mechanics which was fixed. As a result, this should no longer be an issue.
