### ISSUE TITLE
Materials occasionally flicker out of existence

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#760]
As seen in the video below:

https://drive.google.com/open?id=1N4w1nr6LPZiN2CnPj9fBTGN_Mm5fGWDj

**Comment by qreeves** [comment]
I think this is fixed since the change to blending materials. Confirm?

**Comment by Jigoku** [comment]
Looks like it's fixed, can confirm that material faces don't disappear any more as in the video linked above.

**Comment by molexted** [comment]
I've never been able to replicate this bug in the first place, so I'll defer to a confirmation straight from the horse's mouth.

@acerspyro is it still broked?

**Comment by qreeves** [comment]
I changed the draw method from subtractive to blended, which seemed to be the cause of the issue. I haven't seen the bug myself either since.

**Comment by acerspyro** [comment]
I can confirm that this issue is resolved after the changes. Closing.
