### ISSUE TITLE
Missing textures causes desynchronisation of texture edit events

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#792]
Noticed on map @Dziq84's [Kargo map](https://github.com/red-eclipse/world/issues/15).

When someone on the server is missing a texture (since the map contains quite a few new textures), texture edits seem to break, especially when setting a texture to one of the new/missing textures.

This seems random to me, I will have to look into it more and figure out what is going on.

Reproduced on latest Master

**Comment by tellersims222** [comment]
yeah it's messed up.

**Comment by IceflowRE** [comment]
Could be offtopic however.
Copying a custom texture from one map to another can result into another on too afaik.

**Comment by acerspyro** [comment]
@IceflowRE This is normal behaviour, only the slot ID is copied, not the texture source.

**Comment by IceflowRE** [comment]
But maybe worth a look too. Because this is annoying.

**Comment by acerspyro** [comment]
@IceflowRE Please open a new issue on the "forum" about it so we can discuss it further.

**Comment by qreeves** [comment]
Don't use custom textures unless you get them merged into mainline. We will not be adding the ability to get remote textures.

**Comment by IceflowRE** [comment]
> We will not be adding the ability to get remote textures.

Why?

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by acerspyro** [comment]
I don't want them to be sent, I just want them to show as notexture on the problematic client and to sync the vslots properly.

**Comment by qreeves** [comment]
Is this still an issue? The slots all seem to be created properly in the code.
