### ISSUE TITLE
The pumpkin vanity color gets glitchy if you use the "soft" pattern.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/base#797]
- Version and build:  the most recent Master

- Observation: Colors get glitchy.

- Expected result: It should behave normally as with using other patterns.

- How to reproduce: 
1- Select the "soft" pattern, and the pumpkin vanity item.
2- turn down to zero both Red and Green player color values, then mess around with a darker blue.
3- now your pumpkin vanity should be as dark as the blue player color. If the blue color value is too low, the vanity is totally black.

![20180106220400](https://user-images.githubusercontent.com/24359960/34645214-a698c20c-f32e-11e7-95e4-979598ebd381.png)
![20180106220414](https://user-images.githubusercontent.com/24359960/34645215-a6c0cedc-f32e-11e7-9344-eed53166de0a.png)
![20180106220437](https://user-images.githubusercontent.com/24359960/34645216-a6dd4418-f32e-11e7-95e4-b283c061201e.png)

This seems to only occur with the pumpkin model specifically.

**Comment by Jigoku** [comment]
This one can be closed, as it's related to the old pumpkin model

**Comment by molexted** [comment]
Confirmed not applicable to the current version of the game, closing.
