### ISSUE TITLE
better readability in editing stats 

### ISSUE THREAD

**Issue by cloudziq** [redeclipse/base#807]
currently we have something like that:

![redeclipse_2018-01-15_20-34-29](https://user-images.githubusercontent.com/13541407/36685117-acf1382a-1b22-11e8-9d6d-c7da12c7dc89.jpg)

It would be nice to see grid powers with bigger font (or another colour), the same for current amount of cubes selected (that 1 1 1 in second line) and current ents count. Possible to do?

Also I should mention thats these stats are lacking material display like in stable version

**Comment by qreeves** [comment]
Yep :+1:

**Comment by molexted** [comment]
I made it easier to pick out the numbers by graying out the descriptions, used multiplication symbols for the selection volume, fixed selcys (fourth item in parens, second row), and added a raw readout for materials to the second line in 01093b672c0ac49fde1a683d83c8b094802ff3f9.
![editstats](https://user-images.githubusercontent.com/23445929/53546289-ce50d500-3ae0-11e9-8d81-de3fff52779a.png)

If this is not clear enough, let me know what specific colours you want, but I'm going to close the issue.

**Comment by Dziq84** [comment]
by better readability I mean something like that with colours and with only important info (+ current lights rendered entry):
![2019-05-22_16-10-21](https://user-images.githubusercontent.com/13541407/58283776-7eb13b00-7da9-11e9-9bd4-ff637f0fdfab.jpg)
old one for comparison:
![redeclipse_2019-05-23_21-04-45](https://user-images.githubusercontent.com/13541407/58283786-883aa300-7da9-11e9-9194-02c47564ae6e.jpg)

**Comment by q009** [comment]
Solved in new editor
