### ISSUE TITLE
Animation selector for models.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/base#848]
Something that would be quite useful, is to have the ability to select other animations contained with the model, if they are set in the configuration file.
Let's say you have a humanoid model/mesh in the map (like the player character), and you want it to run a certain animation, but currently it isn't possible because it by default plays the "idle" animation.
I wonder how difficult would it be to implement this?

**Comment by Dziq84** [comment]
or better, allow triggers to play anim ID ;p

**Comment by Jigoku** [comment]
I believe this can be done within master branch now.
As for linking a single rail entity to the model, and changing the anim attributes.

**Comment by qreeves** [comment]
Yep.
