### ISSUE TITLE
Wall running/jumping on corners uses all impulse.

### ISSUE THREAD

**Issue by lambda-11235** [redeclipse/base#852]
- Version and build: 1.9.9 cdf28beececa9d68628f8ee09f1881c99d49dbd6
- Observation: If you try to wall jump or run while facing into a corner all impulse is immediately used up.
- Expected result: Only one impulse should be used.
- How to reproduce: Wall jump while facing directly into a wall.

**Comment by acerspyro** [comment]
Tagging for "Stable" as well as the issue is also reproducible on current stable.

I could also reproduce the issue by powersliding on uneven terrain, which often results in impulse being instantly drained.

**Comment by qreeves** [comment]
Probably won't bother backporting a fix to stable, but yeah this is a manifestation of the physics changes as some of the delays have been either shortened or turned off.

**Comment by Jigoku** [comment]
Is this still relevant, as per the impulsemeter/move count changes?

**Comment by molexted** [comment]
Still relevant.

**Comment by q009** [comment]
Is this relevant after recent parkour rewrites?

**Comment by qreeves** [comment]
Nope.
