### ISSUE TITLE
Player characters LOD's implementation

### ISSUE THREAD

**Issue by Dziq84** [redeclipse/base#854]
Since we now have nice LOD system for models, the goal is to add lods for every model in game, including player models. 
I created 4 lod versions (two for male, two for female) but I don't really know how to configure this properly for now :)   any directions or assistance will be appreciated

[Desktop.zip](https://github.com/red-eclipse/base/files/2776186/Desktop.zip)

The distances I suggest for now are:
lod_1  - 128
lod_2  - 512

tris:
player - around 3000
lod_1  - 800
lod_2  - 100  ;p

**Comment by qreeves** [comment]
What do you need to know in order to configure it? _or do I just throw these in with the existing player models?_

**Comment by Dziq84** [comment]
Umm that was easier than I thought, can you add support for disabling vanities over some distance (like 1024 or 768) to make these lods even more usefull?  
I just miss one thing now to finish this, headless models. Does this is just normal player model but without head tris?

**Comment by Jigoku** [comment]
Did you create lods for both the male/female actors hud-body.iqm ?

https://github.com/red-eclipse/actors/tree/master/player/male/headless
https://github.com/red-eclipse/actors/tree/master/player/female/headless

**Comment by Dziq84** [comment]
now only for male, for testing

**Comment by Calinou** [comment]
Is there a meaningful performance difference when using the LOD models? Hiding the vanities at a long distance (depending on the FOV) may be sufficient to improve performance without decreasing quality in a visible manner.
