### ISSUE TITLE
"Rocket jumping" causes gravity to dramatically increase until you touch the ground

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#857]
When rocket jumping (jumping up and launching a rocket under your feet), gravity seems to increase exponentially all the way until you touch the ground, you accelerate towards the ground faster than usual.

I have made a video of the bug here to showcase what is happening https://drive.google.com/file/d/1AswAnTi1x15RYg-Tih9bLoDoAywG2jER/view?usp=sharing

Reproduced on Master

**Comment by qreeves** [comment]
It's not really that gravity is increasing exponentially, but that gravity is a cumulative effect that is stored separately from the velocity, the pushback doesn't reset this currently. It's a matter of choice as to whether it is done or not.

**Comment by qreeves** [comment]
Doesn't seem to be much of a concern either way, so I'll go and make the judgement call. As rocketing jumping is something everyone would generally want, I'll go with resetting the gravity.
