### ISSUE TITLE
Documentation for vdetail

### ISSUE THREAD

**Issue by molexted** [redeclipse/base#890]
The `vdetail` command, which is supposed to allow for detail textures (which should be quite useful) is unfortunately undocumented and I have not been able to get it to work at all. There is also the `texdetail` command which is related and likewise is not documented.

With some briefing on how vdetail works I should be able to add it to the ingame editing reference along with usage.cfg so that it becomes more easily available to mappers.

An example of a working configuration would also be appreciated if one could be provided. I could not find one in Tesseract nor RE.

**Comment by SniperGoth** [comment]
Just to add, this command also appears for models, but i also never found out how they work.

**Comment by Dziq84** [comment]
I think its something for triplanardetail shader (looking at the code)

**Comment by molexted** [comment]
Triplanar and detail are different shaders, see glsl/world.cfg:
https://github.com/red-eclipse/base/blob/d7ef58c0d178fb2ccd7adff6fcc0fd0e08e0691b/config/glsl/world.cfg#L7-L19

In discussion with @q66 on IRC, he had a hunch (though was not certain) that detail needed to be added to the texture config (like in the provided `setshader triplanardetailworld` in world.cfg) and then the vdetail layer defined for a grayscale texture which is then referenced by setting vdetail to a vslot #. I was unable to get this to work, however.

The rationale for triplanar+detail being the only provided means of easily getting the detail shader was explained by that combination being the most useful for texturing large swaths of terrain (which seems plausible to me). This is only speculation, however.

**Comment by Dziq84** [comment]
When I saved a map with 'detailbumbspecmapparallaxworld', engine saved it in config as 'bumpworld'.
But when I used 'triplanardetailbumpspecmapparallaxworld' and saved, this thing is still in map config - thats why I think that vdetail is only for triplanar shader as some sort of parameter and 'detail' can't be used without triplanar present on texture slot

**Comment by molexted** [comment]
Now documented in texture shader guide, closing.
