### ISSUE TITLE
ability to select mapmodels by clicking on model surface

### ISSUE THREAD

**Issue by Dziq84** [redeclipse/base#892]
Currently in many situations it's hard to select adjacent mapmodels. Since engine change + lod support , meshes can be used more widely on maps - thus, after discussion with some other mappers, we think that ability to select mapmodels more comfortably is one of the features that we wish to see in game.

On screen below there are few models as example, forklift + pallet + crate. If you want to move crate or pallet - forklift need to be moved, but then there is no way to align pallet with fork lifts.  in this case mapper need to do /floatspeed 4 (or other small value) to fly very close to pallet (like 1cm) to just select it

![20190624213326](https://user-images.githubusercontent.com/13541407/60047243-8413e500-96c9-11e9-9e86-ea87bd658796.jpg)

Ability to turn out bounding boxes in favor of selecting these objects by polygonal detection is something that can make editing more faster, comfortable - for now its just annoying and not so easy as it should be.
The same can be applied to decal entities (if possible) or just make display of decals bb's always with the same, small size (like with lights or other ents).  Now if decal is enlarged, its BB is large too - obscuring other things you want to select

**Comment by qreeves** [comment]
While I can fix the problem you're having with decal entities, mapmodels are a whole other story. You can't really use `tricollide` conditionally, either the model is set to use it in the config, or it isn't - and it isn't recommended to use it unless you have to due to the processing overhead involved, so you can't just set it on all models to fix the problem.

**Comment by Dziq84** [comment]
so surface clicking on model is not really possible..  bad to hear :/  
If you can make decals bb's disabled that would be great, currently when I use these - I have problems because decals bb's takes out much space and its hard to work with them

**Comment by Jigoku** [comment]
I'm guessing this one could be closed now due to the addition of `entselmapmodelbox` which allows finer movement without the large bounding boxes.

**Comment by molexted** [comment]
It doesn't solve the problem as stated, but AFAIK it's not trivial to do and indeed `entsel<ent>box` fixes this problem, so I'll close it.

**Comment by Dziq84** [comment]
I can suggest adding an optional toggle to models bb's, by enhancing LCTRL key and changing **passthrough** build-in alias a bit.  This way everyone should be satisfied

`editbind LCTRL [entselmapmodelbox 0 ; passthrough 1 ; onrelease [entselmapmodelbox 1 ; passthrough 0] ]`

`passthrough = [
    if (= $arg1 1) [
        oldpassthroughsel = $passthroughsel
        oldpassthroughcube = $passthroughcube
        passthroughsel 1 ; passthroughcube 1
    ] [
        passthroughsel $oldpassthroughsel
        passthroughcube $oldpassthroughcube
    ]
] ; setcomplete passthrough 1`

Reason for this is simple,  not always the new method of selecting mapmodels is ideal, and this method allows to temporary toggle that when LCTRL is pressed - without adding another key bind.
The same key can be used also to toggle **/crosshairdistance** or other small additions

**Comment by Dziq84** [comment]
I can suggest adding an optional toggle to models bb's, by enhancing LCTRL key and changing passthrough build-in alias a bit. This way everyone should be satisfied

editbind LCTRL [entselmapmodelbox 0 ; passthrough 1 ; onrelease [entselmapmodelbox 1 ; passthrough 0] ]

passthrough = [ if (= $arg1 1) [ oldpassthroughsel = $passthroughsel oldpassthroughcube = $passthroughcube passthroughsel 1 ; passthroughcube 1 ] [ passthroughsel $oldpassthroughsel passthroughcube $oldpassthroughcube ] ] ; setcomplete passthrough 1

Reason for this is simple, not always the new method of selecting mapmodels is ideal, and this method allows to temporary toggle that when LCTRL is pressed - without adding another key bind.
The same key can be used also to toggle /crosshairdistance or other small additions

**Comment by Dziq84** [comment]
I can suggest adding an optional toggle to models bb's, by enhancing LCTRL key and changing passthrough build-in alias a bit. This way everyone should be satisfied

editbind LCTRL [entselmapmodelbox 0 ; passthrough 1 ; onrelease [entselmapmodelbox 1 ; passthrough 0] ]

passthrough = [ if (= $arg1 1) [ oldpassthroughsel = $passthroughsel oldpassthroughcube = $passthroughcube passthroughsel 1 ; passthroughcube 1 ] [ passthroughsel $oldpassthroughsel passthroughcube $oldpassthroughcube ] ] ; setcomplete passthrough 1

Reason for this is simple, not always the new method of selecting mapmodels is ideal, and this method allows to temporary toggle that when LCTRL is pressed - without adding another key bind.
The same key can be used also to toggle /crosshairdistance or other small additions
