### ISSUE TITLE
Player in water with thirdperson

### ISSUE THREAD

**Issue by TSnake41** [redeclipse/base#903]
- Version and build: 1.9.9 https://github.com/red-eclipse/base/commit/23f68276c8ef8cdc8658897d34dfc2cd9f33b3b9
- Observation: Player model doesn't display properly when camera is outside the water
- Expected result: Player model display properly in the water
- How to reproduce: Enable thirdperson (`thirdperson 1`) and go to a water pool such as battlefield's one, put the player model inside the water with the camera outside the water.

![image](https://user-images.githubusercontent.com/8642647/63627807-a06cc900-c609-11e9-94f8-392873e7b3f3.png)
Only the half of the model is displayed (everything in the water doesn't display).
The issue doesn't occurs with thirdperson off.

**Comment by Dziq84** [comment]
this is a bit strange since other models and players are visible normally without issues
![20190824012307](https://user-images.githubusercontent.com/13541407/63628684-1a9f4c80-c60e-11e9-8343-13e8e8d34af7.jpg)

**Comment by acerspyro** [comment]
I could be wrong, but I believe the player's own model is rendered in a separate pass from the rest of the world (unless this is only in 1P and not in 3P)

**Comment by qreeves** [comment]
Yeah `player1` is rendered separately from the other players at a different depth index to avoid visual glitches with rendering inside objects, etc.

While `thirdperson` is in the game, it technically isn't officially supported. So the question really is, which graphical glitch is of the most concern: parts of the player being inside objects, or not seeing part of the player in water?

**Comment by Calinou** [comment]
I'd say not seeing part of the player in water is problematic, personally :slightly_smiling_face:
