### ISSUE TITLE
Improve keybindings menu

### ISSUE THREAD

**Issue by PopeRigby** [redeclipse/base#906]
The current keybindings menu is very confusing and as far as I'm aware, doesn't allow for binding to mouse buttons or other inputs devices. I think the game would benefit from a more conventional keybindings menu, where all the game actions are listed out, and you can bind buttons to them by pressing them on your keyboard/mouse/other input device.

**Comment by poVoq** [comment]
I agree, as a of the Steam Beta this is still quite confusing and non standard.

Also why not call it mouse sensitivity as in any other game (currently it is called "camera sensitivity")?

Last but not least: any chance the default parkour button can be changed from "q" to "left-shift"?

Given the difficulties to quickly check the key binds, and the very (in my opinion at least) unnatural way of pressing "Q" for movements (how does one even do that? No way to reach with the little finger), I highly doubt most new-comers will figure out the parkour button at all.

**Comment by molexted** [comment]
There is also a "cursor sensitivity" for the menus which is internally called `mousesensitivity` (I didn't name this) which would be a problem as well.

Lshift is for slide/crouch. I usually use my ring finger for Q and move it up off the A key.

I am rewriting the keybinds UI.

There will be a tutorial level to explain the controls.

**Comment by poVoq** [comment]
Lshift is "walk" in the current default, which is IMHO totally useless :)

**Comment by molexted** [comment]
https://github.com/redeclipse/base/blob/3ef1a8752bb194f479412553d033f2d29295a6a4/config/setup.cfg#L145

**Comment by poVoq** [comment]
Hmm, re-checked and you are right. But "walk" on left ctrl doesn't seem to work at all and all that left-shift seems to do is something like walk but with a slightly lower view-point. Nowhere near what I would call crouch, and I can't get it to slide at all.

**Comment by PopeRigby** [comment]
Yeah, it's hard to tell that you're crouching. Left shift is a pretty strange default for crouch. Usually crouch is bound to Left Ctrl, C, or Alt. I think a good default would be
* Left Ctrl (or C, or Alt) - Crouch
* Left Shift - Parkour/Sprint

**Comment by qreeves** [comment]
The issues on the base repository is not for random musings, it is for confirmed bugs and approved feature requests. Please find a more appropriate area for this discussion or I will have to lock the thread.

**Comment by PopeRigby** [comment]
My bad. Sorry.

**Comment by molexted** [comment]
60fe1a0bb9b1a23876eab0fe6d7bd048f90ead2a
