### ISSUE TITLE
team coloured lights on/off

### ISSUE THREAD

**Issue by Dziq84** [redeclipse/base#924]
This issue has been bothering me for some time. Is there any possibility in the edit mode that you can turn off the team colored lights preview (palletized) as if you were playing FFA? Currently, the only option is to change/vote an ffa mode just to be able to 'see' what the lights look like without team colors. Another option is to change individual lights but it's a bit of a pain. Ideally, it could be toggled some variable.

**Comment by Jigoku** [comment]
I'll mention that thsi PR for allowing trigger/light links, https://github.com/redeclipse/base/pull/1034 

That works in this case, when setting the mode/muts on the linked trigger.

**Comment by Dziq84** [comment]
thank you so much :)   very helpfull feature
