### ISSUE TITLE
Water colours sometimes don't apply correctly

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#925]
When changing watercolour / waterdeepcolour etc; changes are visible in the editor, but sometimes don't apply when the map is loaded in any other game mode.

Eg; `watercolour 255 0 0; waterdeepcolour 255 0 0; savemap; `

Water will then appear bright red in editing mode, but sometimes reverts to the default colours in other modes.

**Comment by Jigoku** [comment]
Closing. Just noticed it was happening with debug binaries. Compiling as normal, it works as expected.

**Comment by Jigoku** [comment]
Ok. So i believe this is a bug, this started happening again with a non-debug build. I've found out that if you keep loading the same map, every now and again, the colour reverts to default settings; see this clip for a visual of what is happening:

https://streamable.com/g35ir

**Comment by qreeves** [comment]
Are you sure this isn't just loading the alternate variant of the map? The variant picked on map load is random, so if you want to copy the settings to the alternate, you need to use `/copyvariantvars`

**Comment by Jigoku** [comment]
You're correct. I wasn't aware of that `/copyvariantvars`, that's useful to know. I assumed the alt/variant settings would only load if the vars were modified. I'll close this then, cheers.
