### ISSUE TITLE
Onslaught enemies keep fighting themselves.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/base#930]
This is something that sometimes i saw happening, but lately, grunts, drones, turrets and rollers keep fighting against themselves, instead of focusing on bots/human players.
To reproduce, load any map with onslaught mutator active, and just watch, as they keep shooting, chasing around and killing their own type.
[100enemy.zip](https://github.com/redeclipse/base/files/3721100/100enemy.zip)
This zip there contains a very small testmap with all of the three types for fast testing/playing.

**Comment by JeffBobbo** [comment]
Hasn't this always been the case though?

**Comment by SniperGoth** [comment]
No, just tested this on 1.6 and they don't kill their own type in any situation. 
1.6:
![20191012170948](https://user-images.githubusercontent.com/24359960/66707220-67043000-ed13-11e9-919c-f93608e405fe.png)

1.9: 
![20191012171134](https://user-images.githubusercontent.com/24359960/66707224-771c0f80-ed13-11e9-90dd-26798bbe9210.png)
