### ISSUE TITLE
spectv not following players in demo mode

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#945]
The spectv camera does not latch onto players whilst spectating a demo match, making it hard/impossible to watch a specific player as you cannot cycle through first/third person views.

Scrolling the mousewheel to switch players results in the camera being dropped at random places.

**Comment by qreeves** [comment]
I'm aware of quite a few SpecTV issues, of which this is one.

**Comment by qreeves** [comment]
@Jigoku Is this still an issue for you with recent SpecTV fixes?

**Comment by Jigoku** [comment]
> @Jigoku Is this still an issue for you with recent SpecTV fixes?

Looks like it's fixed. Spectator camera is now following players fine when swapping between spectating/spectv. :+1:
