### ISSUE TITLE
Sound entities playing sound despite being deleted in map editor

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#949]
If you delete a sound entity, the active sample does not stop playing and continues to loop. If you move outside of the max radius boundary the sound then stops playing.

It would be logical that the sound entity stops playing the sound immediately after it's deleted.

**Reproduce:**
* Add a sound entity
* Delete the sound entity whilst inside the max radius boundary
* The sound will continue to loop indefinitely despite no entity being within the world.

**Comment by Calinou** [comment]
As far as I know, this is also an issue in Sauerbraten (last time I checked).

**Comment by qreeves** [comment]
I've got a fix already in my working copy.
