### ISSUE TITLE
Feature request: Storm mutator

### ISSUE THREAD

**Issue by Minecraft-Beast101** [redeclipse/base#959]
Like a battle royale game, the safe zone closes. You can take varying numbers of damage if you aren't in the safe zone. It is useful for large maps and low numbers of players.

**Comment by molexted** [comment]
This is not the location for these kinds of suggestions, and game design is more complex than implementing random cool features from other games. We are no strangers to other FPS' mechanics, but a more in-depth analysis and reasoning for potential features is required before we consider implementing gameplay features.

There are plans for large map/low player count compensation mechanics, but this is not a viable solution for a multitude of reasons:
- Reliance on items makes contracting boundries problematic
- Inconsistency with other gamemodes
- Layouts not amenable to boundary modifications
