### ISSUE TITLE
Server list UI has twice the value of `sv_serverclients`

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#960]
Setting sv_serverclients to **8** and **32** respectively, the value gets doubled in the UI:
![2019-12-18-110753_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/71082377-e9342900-2188-11ea-8edb-3a2c9bf6bbff.png)

Reproduce: 
Connect to any server and confirm that `serverclients` shows half the value of what is displayed on the server list UI.

This looks like the culprit:
https://github.com/redeclipse/base/blob/0c90a4e6fcc28d0f6ac22e20b032ef8070288944/config/ui/servers.cfg#L79

**Comment by Jigoku** [comment]
Skimming over the server code just now, looks like it's factoring `spectatorslots` (assuming the default/unset value is the same as `serverclients`? hence being doubled)

https://github.com/redeclipse/base/blob/1e157afb8108e15136e4edf2698adcc24b628d1a/src/game/server.cpp#L1229

Is this intended? I'll remove the bug label for now. But i feel it comes across as confusing when setting the server max players, only to see a larger value in the server list.

**Comment by Calinou** [comment]
Indeed, I believe only player slots should be taken into account.

**Comment by Jigoku** [comment]
Also; The default behaviour for sv_serverspectators  (set to 0) appears to double the sv_serverclients value, 

Setting this results in the server list UI showing 16 as the total;
```
sv_serverclients 8
sv_serverspectators 0
```

Whereas this results in the server list UI showing 9 as the total;
```
sv_serverclients 8
sv_serverspectators 1
```

**Comment by qreeves** [comment]
I've made it so `0` is a valid setting and made `-1` double `serverclients` instead. Also defaulting it to `0` so it isn't enabled at all unless the server administrator explicitly requests it.

**Comment by Jigoku** [comment]
I'll reopen this, as the serverspectators value appears to be defaulting to 1.

eg; 
* set `sv_serverspectators 8`, 
set `sv_serverspectators 8`, 
* the server list shows 9 total maxslots
* get one person to enter spectator


I believe the 1 here should be changed to a 0 by default to stop that occurring (not 100% sure though);
https://github.com/redeclipse/base/blob/7b0cfad4347f4556108b961498facce78635c295/src/game/server.cpp#L1228
