### ISSUE TITLE
Optimize "mesh" soluce to include round shapes objects in maps

### ISSUE THREAD

**Issue by Rafirzm** [redeclipse/base#963]
- RE V2.0
- Related discussion: Rift map
- Observation: Bad performance on heavy maps with vegetation
- Expected result: Could add something like a real titanoboa
- How to reproduce: Try on Intel core I5 / I7 proided GPU (Or low performance graphic cards)

```
none
```

**Comment by molexted** [comment]
Turn your `mapeffects` down. This isn't a bug. All maps, including `rift`, fall within their specified performance figures.
