### ISSUE TITLE
Performance is currently terrible. 

### ISSUE THREAD

**Issue by Minecraft-Beast101** [redeclipse/base#965]
Is there any way lag can be reduced? I barely get 40 fps ever with all settings low. I run a quad-core mac mini 2012.

**Comment by molexted** [comment]
The 2012 Mac mini ships with a Core i7-3615M with HD 4000 graphics and is below the listed minimum specs for the game. You can turn down the render scale (in the display tab) to improve framerate, but the performance seems to be about expected.

**Comment by Rafirzm** [comment]
This is somewhat possible due to the network connections, it seem that it can be somehow low on some device.
