### ISSUE TITLE
Red Eclipse 2.0 Available in GNOME Software from fedoraproject.org

### ISSUE THREAD

**Issue by Rafirzm** [redeclipse/base#966]
- Version and build: V2.0
- Related discussion: Gnome software
- Observation: 1.5.6 is available but the 2.0.0 still really is missing
- Expected result: Available at search like the 1.5.6
- How to reproduce: Look up at softwares in the gnome software manager

![Screenshot from 2019-12-21 12-35-14](https://user-images.githubusercontent.com/58426345/71307431-922f8d80-23ee-11ea-946a-d75f3e150289.png)

**Comment by Jigoku** [comment]
You'll have to contact the person who maintains the package for fedora.
More often than not, package maintainers rarely have any ties to the Red Eclipse project and have to be personally contacted.

Doing a quick search [here](https://fedora.pkgs.org/29/fedora-x86_64/redeclipse-1.5.6-7.fc28.x86_64.rpm.html); the listed contact address is  releng@fedoraproject.org

I'd imagine if you sent them an email, they will be able to update the packages to the latest version. But as i said, the Red Eclipse team/developers aren't typically responsible for maintaining those packages on the various Linux distributions.

**Comment by lxqueen** [comment]
Releng is just their automated address for some maintenance tasks I believe.

According to [this page](https://apps.fedoraproject.org/packages/redeclipse/changelog/) on their site though, Pete Walter deals with the Fedora version.

It may also be worth checking in on the Flatpak version (which GNOME Software on Fedora also supports) - which is maintained by @AsciiWolf.

**Comment by AsciiWolf** [comment]
Regarding the Red Eclipse version in Fedora, feel free to create a ticket in [RH Bugzilla](https://bugzilla.redhat.com).

Regarding the version of Red Eclipse on Flathub, I am aware of this, there is already a ticket [opened](https://github.com/flathub/net.redeclipse.RedEclipse/issues/5) about the new version, however I am unfortunately really busy lately. I will try preparing the update once I have some free time. By the way, if anyone from the upstream Red Eclipse devs is interested in push access to the Flathub repo, I will be more than happy to provide it. :-)

**Comment by Calinou** [comment]
@AsciiWolf I could look into it if you're interested :slightly_smiling_face:

**Comment by AsciiWolf** [comment]
@Calinou That would be great, thanks! :-) I will ask Flathub admins to add you the correct permissions for the Red Eclipse Flathub repo.

**Comment by Croydon** [comment]
I think Flathub deserves to be mentioned as a download option

https://github.com/redeclipse/redeclipse.github.io/pull/3
