### ISSUE TITLE
Ammo disappearance effect is triggered on "punch" event with gun

### ISSUE THREAD

**Issue by Rafirzm** [redeclipse/base#975]
Ammo is by effect disappearing on hit with the handgun but no ammo disappears, it only trigger the visual effect...

- Version and build: V2.0
- Related discussion: Unknown
- Observation: This small effect is triggered 
- Expected result: This small effect shouldn't be triggered 
- How to reproduce: Use a handgun and hit the void or another random and useless thing

**Comment by qreeves** [comment]
Not a bug.
