### ISSUE TITLE
system-install-cube2font on Linux doesn't work

### ISSUE THREAD

**Issue by bassmadrigal** [redeclipse/base#988]
- Version and build: 2.0.0
- Related discussion: compiling
- Observation: when running system-install-cube2font on Linux, it errors out saying the file doesn't exist. It tries to install cube2font, when it should be cube2font_linux
- Expected result: It to not error and reference the correct file.
- How to reproduce: Clone repo, build redeclipse, then run system-install-cube2font

My commands that were run:

```
git clone --recurse-submodules -j16 https://github.com/redeclipse/base.git
cd base
make -C src install -j16
make -C src install DESTDIR=/tmp/redeclipse-test prefix=/usr libexecdir=/tmp/redeclipse-test/libexec mandir=/tmp/redeclipse-test/usr/man system-install system-install-cube2font
```

And the output when running the above with just system-install-cube2font:

```
make: Entering directory '/home/jbhansen/program-downloads/base/src'
make: Nothing to be done for 'install'.
mkdir -p /tmp/redeclipse-test/usr/man/man1
gzip -9 -n -c < ../doc/man/cube2font.1 \
        > /tmp/redeclipse-test/usr/man/man1/cube2font.1.gz
mkdir -p /tmp/redeclipse-test/usr/bin
install -m755 cube2font /tmp/redeclipse-test/usr/bin/cube2font
install: cannot stat 'cube2font': No such file or directory
system-install.mk:168: recipe for target 'system-install-cube2font' failed
make: *** [system-install-cube2font] Error 1
make: Leaving directory '/home/jbhansen/program-downloads/base/src'

```

cube2font does not exist after compiling on my system, but src/cube2font_linux does exist. I was able to fix this through my build script by adding the following before building:

```
sed -i 's/m755 cube2font/&_linux/' src/system-install.mk
```

Please advise if this is the best course of action until an official fix is commited.

Thanks
Jeremy

**Comment by Jigoku** [comment]
Yep, looks like the cube2font install command is missing $(BIN_SUFFIX), which would be _linux in this case.

It should probably be:
```install -m755 cube2font$(BIN_SUFFIX) $(bindir)/cube2font```
